# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import (QWidget, QSlider, QLineEdit, QLabel, QPushButton, QScrollArea,QApplication,
                             QHBoxLayout, QVBoxLayout, QMainWindow)
from PyQt5 import QtCore, QtGui, QtWidgets
from k180198_BooleanModel import preprocessing, query_processing

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.stopwords=[]
        self.inverted_index = {}
        self.positional_index= {}
        preprocessing(self.stopwords,self.inverted_index,self.positional_index)


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.run_query = QtWidgets.QPushButton(self.centralwidget)
        self.run_query.setGeometry(QtCore.QRect(570, 20, 121, 41))
        self.run_query.setObjectName("run_query")
        self.Query_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Query_input.setGeometry(QtCore.QRect(120, 30, 411, 31))
        self.Query_input.setObjectName("Query_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(260, 130, 151, 401))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 149, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.document_display = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.document_display.setFont(font)
        self.document_display.setWordWrap(True)
        self.document_display.setObjectName("document_display")
        self.verticalLayout.addWidget(self.document_display)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "18K0198 Boolean Retrieval Model Assignment 1"))
        self.run_query.setText(_translate("MainWindow", "Run Query"))
        #Button Function
        self.run_query.clicked.connect(self.process)

        # self.document_display.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "Matched Documents"))
    
    def process(self):
        _translate = QtCore.QCoreApplication.translate
        query=self.Query_input.text()
        sting=''
        # print(type(query))
        # try:
        Ans=query_processing(query,self.inverted_index,self.positional_index)
        print(Ans)
        
        for A in Ans:
            sting+="Document: "+str(A)+" "
        
        if len(Ans)==0:
            self.document_display.setText(_translate("MainWindow", 'No Matched Documents'))
        else:
            self.document_display.setText(_translate("MainWindow", sting))
        # except:
        # self.document_display.setText(_translate("MainWindow", 'Incorrect Query'))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    input("Press enter to continue...")